### ISSUE TITLE
Templates Manager

### ISSUE THREAD

**Issue by andiamine** [JoomBoost/JoomCCK#10]

**Comment by KEZEO** [comment]
Hello forum  was one the most used feature maybe you could improve it

**Comment by andiamine** [comment]
Hi my friend, yes we are going to update all packs.

**Comment by Giorgi625** [comment]
Yes forum is great feature, but older versions forum was quite weak in features. It will need some features to be added to have good forum. later I will post my suggestions.

**Comment by andiamine** [comment]
Yes any new suggestions will help, currently we will focus to make the products stable and alive :)
