### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by andiamine** [JoomBoost/JoomCCK#14]
Update notifications feature to support J4 and BS5

**Comment by Giorgi625** [comment]
Notifications is one of my favorite features but when sending notifications(on Cobalt 8) to mails it only sends status of notification and title of record. no image or desc for example. will be good if we will be able to create template for email notifications as well in JoomCCK, like they did it in Joomla 4 for core emails feature.

**Comment by andiamine** [comment]
Yes good idea surely we will add integration with Joomla Email Templates
https://github.com/orgs/JoomBoost/projects/3
